sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: vETEZQDlRR9QbEcvsW62hTBEsVXjJPscd93EOFEnok0Zu4ganN6zP3fJuoj9IoFbv8ofBnlROJq3KK6dYeEYMaM6jXy8xvkd8f4XtsdIRxH0OcrBN26QpSPyA0uRK0myRQKnxcPAmEdFU0zrFsxvCLDRitB8RDqWz/eCSGIy+Frcga5O6w9chZUn8iKVpS3pXnMxlCMHsNgO24Amuoy9xgJOqlpPp94oc+EA1zKiAZ07NlNv6eCdarlXDmoieoQsgDqR2iLUotGaR6XYMGiy4ndc6aUN9Cl/pZe6CrJrzSies/z6/jj+NgYCe/foQZu2s3ByFpkMtFnBiAjAGmuh4Pwg6ytzhMT3rKp8LmIChnYCsHyBaKphOWqgYl1sKiQx1o/j6ezFOXKrTZjmE/eZ3P2xtsIBK1uOBH2vT8NVuOusdGkbehfL6SSEmTH7dfiDklml+wzaI1dZADVt8BMNqZCK6YFFhnBW1o8Q8UveuNEb8R9lX5clWSkw3o5lxsp2cWibRrcnb1FxREb0U8ukWiDP7nFqbYPM4SAFZP4iYBDf6dirkb3F22tkcuiRONVuprmzJP6GeXsOWYdPm5Gsab6WuqGIRGzsTk5oBZhItd7TZ7gcFv43MB31VjLdNyTFWs1Ueh8SxgPnMCvg7pup2daj14tjNXGnrAe3EC/s/co=
  - secure: gJwAm4GNVJPPZYnTLszk6g7Sd7h9K1jzaSSvuAhKXUULQCI0ZO52NHn/0/zL/nWmnLQQYnbh7p7Fnsf8N3gaRFeU7y83qs9wL5wfJ8E2ZGttUITSkH8JyCo4ZuRpGETCufYLFcRq1ksCKa2Ty6oBUZCNSe39oDprsi718SOM5r6MSDQpTNfpEkUiG1xZ6BvGb7r16nrZUCqaBxyFjWHbbFsMoPCX8rRw4baHHLymwtuWiIOk8f9cO5PMLZ9Gzrv1x7gEH1djmkwJ7w9j7tJP6fXU+4NE+y38ObEXlabwl7+lt+p1sfmghCrvb/lfobQNpKAEDtAHvYrwQqXWOE1pyEMfWzNW907sea9UYG0KAQUcG6gB5yfci8bwX8UDuyYFtQVryfPRZxoAxnEmH5XwtYmTVCvde1OYCZ3NbC1iyu3YnFT5ioxISN30WoKqJjvYyqjIOGD8ZDjlTkyQFOExJyptdtsZk/wES/uyOYuoWpDw6MRQUE5OSsrr7Ffsc2rA0JxaDW6RRRbPvCxVXAZuzKS1OosC1r1u4OLRX+NoMlANZFhr/b1m36tKHYq4RMTTthE8gUAWhEl+NKCtiNeTppTZXK1J8P8b/3jgFM6/NUAXt9IIpXxMbyI2330WsbzmLuDUIm6VxaTz86aDOZP2wsL4feh9vd2h5IPcmHMI3Bo=
